/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_myproject_MyActivity */

#ifndef _Included_com_myproject_MyActivity
#define _Included_com_myproject_MyActivity
#ifdef __cplusplus
extern "C" {
#endif
#undef com_myproject_MyActivity_HANDLER_SHOW_DIALOG
#define com_myproject_MyActivity_HANDLER_SHOW_DIALOG 1L
/*
 * Class:     com_myproject_MyActivity
 * Method:    onSimpleKeyPressed
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_myproject_MyActivity_onSimpleKeyPressed
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
