/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_myproject_MyActivity */

#ifndef _Included_com_myproject_MyActivity
#define _Included_com_myproject_MyActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_myproject_MyActivity
 * Method:    getMyData
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_myproject_MyActivity_getMyData
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
